// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dartJJ
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9Iwt-SBA2fWEtGpfiz02D0Wpq-xzwDQ',
    appId: '1:711521421896:web:2d2871cca62c9c4ff9267d',
    messagingSenderId: '711521421896',
    projectId: 'satti-ecom',
    authDomain: 'satti-ecom.firebaseapp.com',
    storageBucket: 'satti-ecom.firebasestorage.app',
    measurementId: 'G-2ZQ3622CCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtcMKvTwfG-8iUdwV8H12XStmJsz-QPw',
    appId: '1:711521421896:android:94b544fed8be41a0f9267d',
    messagingSenderId: '711521421896',
    projectId: 'satti-ecom',
    storageBucket: 'satti-ecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0KWpS6pfnW2aC_v3WUUBAbaT1qn0W9qs',
    appId: '1:711521421896:ios:2e6dd61896bea9a8f9267d',
    messagingSenderId: '711521421896',
    projectId: 'satti-ecom',
    storageBucket: 'satti-ecom.firebasestorage.app',
    iosBundleId: 'com.example.airdepart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0KWpS6pfnW2aC_v3WUUBAbaT1qn0W9qs',
    appId: '1:711521421896:ios:2e6dd61896bea9a8f9267d',
    messagingSenderId: '711521421896',
    projectId: 'satti-ecom',
    storageBucket: 'satti-ecom.firebasestorage.app',
    iosBundleId: 'com.example.airdepart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd9Iwt-SBA2fWEtGpfiz02D0Wpq-xzwDQ',
    appId: '1:711521421896:web:220d5e37a558dbbcf9267d',
    messagingSenderId: '711521421896',
    projectId: 'satti-ecom',
    authDomain: 'satti-ecom.firebaseapp.com',
    storageBucket: 'satti-ecom.firebasestorage.app',
    measurementId: 'G-1NTQGNXT7T',
  );
}
