import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/products_provider.dart';
import '../models/product.dart';

class SettingsScreen extends ConsumerStatefulWidget {
  final String username; 
  const SettingsScreen({Key? key, required this.username}) : super(key: key);

  @override
  ConsumerState<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends ConsumerState<SettingsScreen> {
  // --- THEME COLORS ---
  static const colorBackground = Color(0xFFF5F5F7);
  static const colorDarkGreen = Color(0xFF1E3A34);
  static const colorBlack = Color(0xFF000000);

  // --- FORM STATE ---
  final _formKey = GlobalKey<FormState>();
  bool _isLoading = false;

  final _nameController = TextEditingController();
  final _priceController = TextEditingController();
  final _descController = TextEditingController();
  final _imageController = TextEditingController();

  // Dropdown Data
  String _selectedGender = 'Men';
  String _selectedCategory = 'Jackets';

  final Map<String, List<String>> _categoriesMap = {
    'Men': ['Jackets', 'Shoes', 'Perfumes', 'Suits', 'Accessories'],
    'Women': ['Jewelry', 'Jackets', 'Western', 'Bags', 'Footwear'],
  };

  @override
  void initState() {
    super.initState();
    _selectedCategory = _categoriesMap['Men']!.first;
  }

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final newProduct = Product(
        id: '', // Generated by Firebase
        name: _nameController.text.trim(),
        description: _descController.text.trim(),
        price: double.parse(_priceController.text.trim()),
        imageUrl: _imageController.text.trim(),
        gender: _selectedGender,
        category: _selectedCategory,
      );

      await ref.read(productsProvider.notifier).addProduct(newProduct);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Product added successfully!')),
        );
        _nameController.clear();
        _priceController.clear();
        _descController.clear();
        _imageController.clear();
      }
    } catch (error) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $error')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    const modernStyle = TextStyle(fontFamily: 'Arial', color: colorBlack);

    return Scaffold(
      backgroundColor: colorBackground,
      appBar: AppBar(
        backgroundColor: colorBackground,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: colorBlack),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text("SETTINGS", style: modernStyle.copyWith(fontWeight: FontWeight.bold)),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            
            // --- USER INFO CARD ---
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: colorDarkGreen,
                borderRadius: BorderRadius.circular(20),
              ),
              child: Row(
                children: [
                  Container(
                    width: 60, height: 60,
                    decoration: const BoxDecoration(color: Colors.white, shape: BoxShape.circle),
                    child: const Icon(Icons.person, size: 30, color: colorDarkGreen),
                  ),
                  const SizedBox(width: 16),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text("LOGGED IN AS", style: modernStyle.copyWith(color: Colors.white54, fontSize: 10)),
                      Text(widget.username, style: modernStyle.copyWith(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 4),
                      Text("Admin Privileges Active", style: modernStyle.copyWith(color: Colors.greenAccent, fontSize: 12)),
                    ],
                  )
                ],
              ),
            ),

            const SizedBox(height: 30),
            const Divider(color: Colors.grey),
            const SizedBox(height: 20),

            // --- ADD PRODUCT FORM ---
            Text("ADD NEW ITEM", style: modernStyle.copyWith(fontSize: 24, fontWeight: FontWeight.w900)),
            const SizedBox(height: 20),

            Form(
              key: _formKey,
              child: Column(
                children: [
                  _buildInput(_nameController, "Product Name"),
                  const SizedBox(height: 12),
                  _buildInput(_priceController, "Price", isNumber: true),
                  const SizedBox(height: 12),
                  _buildInput(_descController, "Description"),
                  const SizedBox(height: 12),
                  _buildInput(_imageController, "Image URL"),
                  const SizedBox(height: 20),

                  // --- GENDER DROPDOWN ---
                  DropdownButtonFormField<String>(
                    initialValue: _selectedGender,
                    dropdownColor: Colors.white,
                    decoration: _inputDecoration("Section / Gender"),
                    items: ['Men', 'Women'].map((gender) => DropdownMenuItem(
                      value: gender,
                      child: Text(gender, style: modernStyle),
                    )).toList(),
                    onChanged: (val) {
                      setState(() {
                        _selectedGender = val!;
                        // Reset category to first item of new gender
                        _selectedCategory = _categoriesMap[_selectedGender]!.first;
                      });
                    },
                  ),
                  const SizedBox(height: 12),

                  // --- CATEGORY DROPDOWN (Dynamic) ---
                  DropdownButtonFormField<String>(
                    initialValue: _selectedCategory,
                    dropdownColor: Colors.white,
                    decoration: _inputDecoration("Category"),
                    items: _categoriesMap[_selectedGender]!.map((cat) => DropdownMenuItem(
                      value: cat,
                      child: Text(cat, style: modernStyle),
                    )).toList(),
                    onChanged: (val) => setState(() => _selectedCategory = val!),
                  ),

                  const SizedBox(height: 30),

                  // --- SUBMIT BUTTON ---
                  SizedBox(
                    width: double.infinity,
                    height: 55,
                    child: ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        backgroundColor: colorBlack,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(30)),
                      ),
                      onPressed: _isLoading ? null : _submitForm,
                      child: _isLoading 
                        ? const CircularProgressIndicator(color: Colors.white)
                        : const Text("PUBLISH PRODUCT", style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                    ),
                  )
                ],
              ),
            ),
            const SizedBox(height: 50),
          ],
        ),
      ),
    );
  }

  // Helper for text fields
  Widget _buildInput(TextEditingController controller, String label, {bool isNumber = false}) {
    return TextFormField(
      controller: controller,
      keyboardType: isNumber ? TextInputType.number : TextInputType.text,
      decoration: _inputDecoration(label),
      validator: (val) {
        if (val == null || val.isEmpty) return 'Required';
        return null;
      },
    );
  }

  InputDecoration _inputDecoration(String label) {
    return InputDecoration(
      labelText: label,
      labelStyle: const TextStyle(color: Colors.grey),
      filled: true,
      fillColor: Colors.white,
      enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Colors.transparent)),
      focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFF1E3A34))),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
    );
  }
}